login/urls.py
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
    path('', views.login, name='login'),
    path('log/', views.log, name='log'),
    path('ListCS/', views.ListCS, name='ListCS')

]

website/urls.py
from django.contrib import admin
from django.urls import include, path
#from login import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include("login.urls")),
]

login/models.py
from django.db import models

# Create your models here.


class Users(models.Model):
    userTel = models.CharField(primary_key=True, max_length=12)
    userName = models.CharField(max_length=16)
    userMail = models.CharField(max_length=20)
    userPwd = models.CharField(max_length=20)


class Cs(models.Model):
    csId = models.IntegerField(primary_key=True)
    csAdd = models.CharField(max_length=50)
    csStates = models.BooleanField()
    csFreeTime = models.TimeField


class UserCs(models.Model):
    userTel = models.ForeignKey(Users, on_delete=models.DO_NOTHING)
    csId = models.ForeignKey(Cs, on_delete=models.DO_NOTHING)

login/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse,HttpResponseRedirect
from django import forms
from login.models import Users
from django.template import RequestContext
# Create your views here.


def index(request):
    return render(request, 'index.html')


def login(request):
    return render(request, 'login.html')


def ListCS(request):
    return render(request, 'ListCS.html')


class userForm(forms.Form):
    inputTel = forms.CharField(label='inputTel', max_length=12)
    inputPassword = forms.CharField(label='inputPassword', widget=forms.PasswordInput())


def log(req):
    if req.method == 'POST':
        uf = userForm(req.POST)
        if uf.is_valid():
            inputTel = uf.cleaned_data['inputTel']
            inputPassword = uf.cleaned_data['inputPassword']
            user = Users.objects.filter(userTel=inputTel, userPwd=inputPassword)
            if user:
                response = HttpResponseRedirect('/login/log/')
                response.set_cookie('inputTel', inputTel, 3600)
                req.session['inputTel'] = "inputTel"
                return render(req, 'index.html')
            else:
                return HttpResponseRedirect('login/navbar/')
    else:
        uf = Form()
    return HttpResponseRedirect('/login/')

templates/ListCS.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <style>

        body {
            background-color: aliceblue;
        }

        #Home {
            margin-left: 8.4%;
        }

        #user:hover, #user:focus {
            color: #FFFF;
            text-decoration: none;
        }

        #user {
            position: absolute;
            font-size: large;
            color: #9d9d9d;
            right: 4%;
            top: 25%;

        }

        .logo {
            position: absolute;
            right: 10%;
            top: 5px;
            width: 40px;
            height: 40px;
            border-radius: 100px;
        }

        .logo:hover {
            width: 42px;
            height: 42px;
        }

        .dropdown-menu {
            margin-top: 50px;
            left: 90%;
            right: 0px;
        }

        .page {
            margin-top: 60%;

        }

        .logoMark {
            width: 100px;
            height: 100px;
            margin-top: 10%;
            border-radius: 100px;
        }

        .listCS {
            margin-top: 1%;
            background-color: aqua;
        }

        .ls {
            font-size: large;
            margin-top: 30px;
            margin-left: 5%;
            text-align: center;
        }

        .listNav {
            margin-top: 1%;
        }

        .csid {
            text-align: center;
        }


    </style>


</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="nav-header">

            <img class="logo" src="{% static "/img/logo.png" %}">

            <a href="#" id="user" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
               aria-expanded="false">lvscf </a>
            <div class="dropdown">
                <ul class="dropdown-menu">
                    <li><a href="#">修改信息</a></li>
                    <li><a href="#">切换用户</a></li>
                    <li><a href="#">退出</a></li>
                </ul>
            </div>
           <a class="navbar-brand" id="Home" href="#">Home</a> {% comment %}页面跳转去主页{% endcomment %}
        </div>

    </div>
</nav>


<div class="container-fluid">
    <div class="row">
        <div class="col-md-1 "></div>
        <div class="col-md-2 sbe">

            <img class="logoMark center-block" src="{% static "/img/logo.png" %}">
            <ul class="nav  nav-stacked ls ">
                <li><a href='#'>第一个选项</a></li>
                <li><a href='#'>第二个选项</a></li>
                <li><a href='#'>第三个选项</a></li>
            </ul>

        </div>
        <div class="col-md-1 "></div>
        <div class="col-md-7 listCS">

            <ul class="nav nav-tabs listNav">
                <li role="presentation" class="active"><a href="#">所有充电桩</a></li>
                <li role="presentation"><a href="#">空闲中</a></li>
                <li role="presentation"><a href="#">已关注</a></li>
            </ul>

            <div class="panel panel-default ">
                <!-- Default panel contents -->

                <!-- Table -->
                <table class="table ">
                    <tr>
                        <th>充电桩编号</th>
                        <th>充电桩位置</th>
                        <th>空闲状态</th>
                        <th>距离空闲时间</th>
                        <th>是否关注</th>
                    </tr>
                    <tr>
                        <td class="csid">1</td>
                        <td>博文苑8号楼7号桩</td>
                        <td>是</td>
                        <td>无</td>
                        <td>
                            <div class="make-switch" data-on-label="开" data-off-label="关" id="toggle-state-switch"
                                 data-on="success" data-off="warning">
                                <input id="toggle" type="checkbox" checked="checked" class="toggle"/>
                            </div>
                        </td>
                    </tr>
                      <tr>
                        <td class="csid">2</td>
                        <td>博文苑8号楼8号桩</td>
                        <td>否</td>
                        <td>1:32:23</td>
                        <td>
                            <div class="make-switch" data-on-label="开" data-off-label="关" id="toggle-state-switch"
                                 data-on="success" data-off="warning">
                                <input id="toggle" type="checkbox" checked="checked" class="toggle"/>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>

            <nav class="page" aria-label="Page navigation">
                <ul class="pagination">
                    <li>
                        <a href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li>
                        <a href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
        </div>


        <div class="col-md-1"></div>
    </div>
</div>


</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>welcome {{Users.inputTel}} </h1>
</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static "css/login.css"%}">
</head>
<body >


     <div class="register">
         <a id="register1" href="#">注册</a>
         <a href="#">忘记密码</a>
     </div>

     <form class="form-signin text-center" action="{% url 'login:log' %}"  method = 'post'>
          {% csrf_token %}
          {{uf.as_p}}
         <img class="logo" src="{% static "/img/logo.png"%}">
         <h1 class="h3 mb-3 font-weight-normal">欢迎登陆</h1>
         <label for="inputTel" class="sr-only">Telephone</label>
         <input type="tel" id="inputTel" name="inputTel" class="form-control" placeholder="Telephone" >
         <label for="inputPassword" class="sr-only">Password</label>
         <input type="password" name="inputPassword" id = "inputPassword" class="form-control" placeholder="Password" required>
         <div class="checkbox mb-3">
             <label>
                 <input type="checkbox" value="remember-me"> 记住密码
             </label>
         </div>
         <button class="btn btn-lg btn-primary btn-block" type="submit" id="login"  >登录</button>

         <div class="myMark">充电桩</div>
     </form>


</body>
</html>

templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Bootstrap导航条鼠标悬停下拉菜单</title>
	<link id="bootstrap_221" rel="stylesheet" type="text/css" class="library" href="http://apps.bdimg.com/libs/bootstrap/3.3.4/css/bootstrap.min.css">
	<script id="jquery_172" type="text/javascript" class="library" src="http://apps.bdimg.com/libs/jquery/1.9.1/jquery.min.js"></script>
	<script id="bootstrap_221" type="text/javascript" class="library" src="http://apps.bdimg.com/libs/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	<style type="text/css">
		.navbar .nav > li .dropdown-menu {
			margin: 0;
		}
		.navbar .nav > li:hover .dropdown-menu {
			display: block;
		}
	</style>
</head>
<body>
	<div class="container">
		<div class="navbar">
			<div class="navbar-inner">
				<ul class="nav nav-pills">
				   <li class="active"><a href="#">Home</a></li>
				   <li class="dropdown"><a href="#">SVN<span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="#">sub SVN1</a></li>
							<li><a href="#">sub SVN2</a></li>
						</ul>
				   </li>
				   <li><a href="#">iOS</a></li>
				   <li><a href="#">VB.Net</a></li>
				   <li class="dropdown"><a href="#">Java<span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="#">sub Java1</a></li>
							<li><a href="#">sub Java2</a></li>
						</ul>
				   </li>
				   <li><a href="#">PHP</a></li>
				</ul>
			</div>
		</div>
	</div>
</body>
</html>